import { NextRequest, NextResponse } from "next/server"
import { Resend } from "resend"

// Initialize Resend
const resend = process.env.RESEND_API_KEY ? new Resend(process.env.RESEND_API_KEY) : null

export async function POST(request: NextRequest) {
  const startTime = Date.now()

  try {
    const { email, name } = await request.json()

    if (!email || !name) {
      return NextResponse.json({ error: "Email and name are required" }, { status: 400 })
    }

    // Initialize AgentMail SDK dynamically
    let agentmail: any = null
    if (process.env.AGENTMAIL_API_KEY) {
      try {
        const { AgentMailClient } = require("agentmail")
        agentmail = new AgentMailClient({ apiKey: process.env.AGENTMAIL_API_KEY })
        console.log("[AgentMail] SDK initialized successfully")
      } catch (err) {
        console.error("[AgentMail] SDK initialization error:", err)
      }
    } else {
      console.log("[AgentMail] No API key found in environment")
    }

    // Check if we have API keys
    const hasResend = !!process.env.RESEND_API_KEY
    const hasAgentMail = !!process.env.AGENTMAIL_API_KEY && !!agentmail

    console.log("[Email API] hasAgentMail:", hasAgentMail, "hasResend:", hasResend)
    console.log("[Email API] agentmail object:", !!agentmail)

    let emailSent = false
    let emailId = null
    let service = "Demo Mode"

    // Try AgentMail first if available
    if (hasAgentMail && agentmail) {
      console.log("[AgentMail] Attempting to send email...")
      try {
        // AgentMail requires creating/using an inbox
        // For demo purposes, create a new inbox for each email (you can cache this in production)
        const inbox = await agentmail.inboxes.create({
          name: "Photography Agent",
        })

        console.log(`[AgentMail] Inbox created: ${inbox.email}`)

        // Now send email from this inbox
        const result = await agentmail.emails.send({
          from_email: inbox.email,
          to_email: email,
          subject: `Photography Quote for ${name}`,
          body: `
Hi ${name}!

Thanks for your interest in our photography services. Our AI agent has prepared a personalized quote for you!

📋 Proposed Package:
- 2-hour professional photoshoot
- Multiple outfit changes
- Various locations around campus/city
- 50+ edited high-resolution photos
- Online gallery for easy sharing

Investment: $450

Available Dates:
• April 15th, 2024
• April 18th, 2024

Would either of these dates work for you? I'd love to capture your special moments!

---
⚡ This email was automatically generated by our AI agent system powered by AgentMail!

Best,
Contrast Photography Team
          `,
        })

        emailSent = true
        emailId = result?.id || inbox.id
        service = "AgentMail"
        console.log("[AgentMail] Email sent successfully from:", inbox.email)
        console.log("[AgentMail] Email ID:", emailId)
      } catch (err: any) {
        console.error("[AgentMail] Error:", err)
        console.error("[AgentMail] Error details:", err.message)
        console.error("[AgentMail] Full error:", JSON.stringify(err, null, 2))
      }
    }

    // Try Resend if AgentMail failed or not available
    if (!emailSent && hasResend && resend) {
      try {
        const { data, error } = await resend.emails.send({
          from: process.env.FROM_EMAIL || "Contrast Demo <onboarding@resend.dev>",
          to: [email],
          subject: `Photography Quote for ${name}`,
          html: `
            <div style="font-family: system-ui, -apple-system, sans-serif; max-width: 600px; margin: 0 auto; padding: 40px 20px;">
              <div style="text-align: center; margin-bottom: 40px;">
                <h1 style="color: #37352F; font-size: 32px; margin: 0;">📸 Contrast</h1>
                <p style="color: #787774; margin: 10px 0 0 0;">Photography Coordinator</p>
              </div>

              <h2 style="color: #37352F; font-size: 24px; margin: 0 0 20px 0;">Hi ${name}!</h2>
              
              <p style="color: #37352F; line-height: 1.6; margin: 0 0 20px 0;">
                Thanks for your interest in our photography services. Our AI agent has prepared a personalized quote for you!
              </p>

              <div style="background: #F7F6F3; border-radius: 8px; padding: 24px; margin: 30px 0;">
                <h3 style="color: #37352F; font-size: 18px; margin: 0 0 16px 0;">📋 Proposed Package</h3>
                <ul style="color: #37352F; line-height: 1.8; margin: 0; padding-left: 20px;">
                  <li>2-hour professional photoshoot</li>
                  <li>Multiple outfit changes</li>
                  <li>Various locations around campus/city</li>
                  <li>50+ edited high-resolution photos</li>
                  <li>Online gallery for easy sharing</li>
                  <li>Unlimited downloads</li>
                </ul>
              </div>

              <div style="background: linear-gradient(135deg, #2383E2 0%, #1a6bc4 100%); border-radius: 8px; padding: 24px; margin: 30px 0; text-align: center;">
                <p style="color: white; font-size: 14px; margin: 0 0 8px 0; text-transform: uppercase; letter-spacing: 1px;">Investment</p>
                <p style="color: white; font-size: 42px; font-weight: bold; margin: 0;">$450</p>
              </div>

              <p style="color: #37352F; line-height: 1.6; margin: 20px 0;">
                <strong>Available Dates:</strong><br>
                • April 15th, 2024<br>
                • April 18th, 2024
              </p>

              <p style="color: #37352F; line-height: 1.6; margin: 30px 0 20px 0;">
                Would either of these dates work for you? I'd love to capture your special moments!
              </p>

              <div style="text-align: center; margin: 40px 0;">
                <a href="mailto:hello@contrastphotography.com?subject=Booking%20for%20${encodeURIComponent(name)}" 
                   style="display: inline-block; background: #2383E2; color: white; padding: 14px 32px; border-radius: 6px; text-decoration: none; font-weight: 600;">
                  Book Your Session →
                </a>
              </div>

              <hr style="border: none; border-top: 1px solid #E9E9E7; margin: 40px 0;">

              <div style="background: #FFF9E6; border-left: 4px solid #FFC700; border-radius: 4px; padding: 16px; margin: 20px 0;">
                <p style="color: #8B6914; font-size: 14px; margin: 0; line-height: 1.5;">
                  <strong>⚡ Demo Note:</strong> This email was automatically generated by our AI agent system 
                  as proof of real-time integration. You're experiencing the future of automated business coordination!
                </p>
              </div>

              <div style="text-align: center; margin-top: 40px; padding-top: 20px; border-top: 1px solid #E9E9E7;">
                <p style="color: #9B9A97; font-size: 12px; margin: 0;">
                  Sent via Contrast AI Photography Coordinator<br>
                  ${new Date().toLocaleString()}
                </p>
              </div>
            </div>
          `,
        })

        if (error) {
          console.error("[Resend] Error:", error)
        } else {
          emailSent = true
          emailId = data?.id
          service = "Resend"
        }
      } catch (err) {
        console.error("[Resend] Error:", err)
      }
    }

    // Demo mode if no API keys
    if (!emailSent && !hasResend && !hasAgentMail) {
      await new Promise((resolve) => setTimeout(resolve, 1500))
      service = "Demo Mode (No API keys - set RESEND_API_KEY or AGENTMAIL_API_KEY)"
    }

    const duration = Date.now() - startTime

    console.log(`[${service}] Email ${emailSent ? "sent" : "simulated"} to ${email} in ${duration}ms${emailId ? ` - ID: ${emailId}` : ""}`)

    return NextResponse.json({
      success: true,
      duration,
      message: emailSent ? "Email sent successfully" : "Email simulated (demo mode)",
      details: {
        to: email,
        subject: `Photography Quote for ${name}`,
        timestamp: new Date().toISOString(),
        service,
        emailId,
        realEmail: emailSent,
      },
    })
  } catch (error) {
    const duration = Date.now() - startTime
    console.error("[Email] Error:", error)

    return NextResponse.json(
      {
        success: false,
        duration,
        error: "Failed to send email",
      },
      { status: 500 },
    )
  }
}

